// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: iyjivtmjlkfclbdavfsp

class SupabaseConfig {
  static const String supabaseUrl = 'https://iyjivtmjlkfclbdavfsp.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5aml2dG1qbGtmY2xiZGF2ZnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NjQzOTUsImV4cCI6MjA3NzE0MDM5NX0.oX18VuQlNmSlo9en4x7G8XRx_MKRyXKSkYP72mNhzFM';
}
